### ISSUE TITLE
Link to mqtt_to_influxdb.py file on Grafana for Visualization page is invalid

### ISSUE THREAD

**Issue by synaptiko** [bigclownlabs/bc-website#14]
I'd like to run Grafana setup with BigClown but unfortunately I'm not able to find the script the documentation is referring to in `content/doc/integrations/grafana-for-visualization.md`:

> Get the Python source for the gateway (mqtt_to_influxdb.py@GitHub) from MQTT (Mosquitto) to InfluxDB. And make it executable.

The link leads to [https://github.com/bigclownlabs/bcf-climate-station/blob/master/hub/mqtt_to_influxdb.py](https://github.com/bigclownlabs/bcf-climate-station/blob/master/hub/mqtt_to_influxdb.py). There is [https://github.com/bigclownlabs/bcf-kit-wireless-climate-monitor](https://github.com/bigclownlabs/bcf-kit-wireless-climate-monitor) now but it doesn't contain this file anymore.

**Comment by synaptiko** [comment]
The link below on the same page is also invalid:

> Download and install from BigClown GitHub new SystemD service describing how to run the MQTT to InfluxDB gateway (mqtt_to_influxdb.service).

**Comment by synaptiko** [comment]
And those ones :-)

> At first download grafana-climate-station.json directly of review it at GitHub and get using the raw link.

- https://github.com/bigclownlabs/bcf-climate-station/raw/master/hub/grafana-climate-station.json
- https://github.com/bigclownlabs/bcf-climate-station/blob/master/hub/grafana-climate-station.json

**Comment by hubpav** [comment]
Do you use our BigClown Raspbian? I asked my colleague @blavka and he said, there are bootstrap scripts in the `install` folder.

**Comment by synaptiko** [comment]
No, I don't. But thanks for the hint, I found the scripts here: https://github.com/bigclownlabs/bc-raspbian/tree/master/install and here: https://github.com/blavka/bcp-monitor-in-docker

I think I'm able to use it. But it would be great to update the docs too :-)

**Comment by jfrantisek** [comment]
Hello, link to [grafana-climate-station.json](https://github.com/bigclownlabs/bcf-climate-station/raw/master/hub/grafana-climate-station.json) is dead too on page [grafana-for-visualization](https://www.bigclown.com/doc/integrations/grafana-for-visualization/).

**Comment by hubpav** [comment]
Hi guys, thanks for pointing this out - we will prioritize this Grafana tutorial.

**Comment by blavka** [comment]
All fixed,
new documentation is on https://www.bigclown.com/doc/integrations/grafana-for-visualization/
