### ISSUE TITLE
wireless-led-strip.md node-red example code is a duplicate of the setup code

### ISSUE THREAD

**Issue by oliverjc** [bigclownlabs/bc-website#17]
The code [here](https://www.bigclown.com/doc/projects/wireless-led-strip/) for [this](https://www.bigclown.com/doc/projects/wireless-led-strip/radio-test.png) flow is a duplicate of the [pairing flow](https://www.bigclown.com/doc/projects/wireless-led-strip/node-red-gw-pair-stop.png)

**Comment by hubpav** [comment]
Hi @oliverjc - thanks a lot for letting us know. We just fixed it. Let me know if it works for you. Thank you!
