### ISSUE TITLE
Problems with docs should be solved with GH Issues

### ISSUE THREAD

**Issue by berkas1** [bigclownlabs/bc-website#2]
Footer of documentation pages says "Byl článek nesrozumitelný nebo nešlo něco udělat?..." and encourages people to discuss problems with particular tutorial over mail. I think we should encourage users to discuss problems here (and not with mail), with the help of Github Issues, because:

- discussion will be public and more users can say their opinion (and "víc hlav víc ví", dont know the english equivalent)
- we can track issues with tutorials that have already been fixed

We can change this to "use github issues" or "use github issus or send a mail".

What do you think?

**Comment by hubpav** [comment]
I fully agree here and I prefer to encourage people to discuss the content on GH issues in the first place. I will fix the sentence. Thx!
