### ISSUE TITLE
CoreModule Gateway 1.8 automatic-pairing start

### ISSUE THREAD

**Issue by zkul** [bigclownlabs/bc-website#31]
Hi,
the automatic_pairing_start() method sends
usb_talk_send_string("[\"/pairing-mode\", \"stop\"]\n");
Should be
usb_talk_send_string("[\"/automatic-pairing\", \"start\"]\n");

regards
Zdenek

**Comment by blavka** [comment]
Yes,
it's a bug, I'll fix it.
