### ISSUE TITLE
Cloony pinout wrong

### ISSUE THREAD

**Issue by vavravl1** [bigclownlabs/bc-website#36]
The cloony pinout drawn here (https://www.bigclown.com/doc/hardware/header-pinout/) is not the same as in the schematics here (https://github.com/bigclownlabs/bc-hardware/blob/master/out/bc-cloony/bc-cloony-rev-1-0.pdf). At least with respect to the SDA0,SCL0 signals.

The pinout in the schematics seems to be the correct one.

**Comment by hubmartin** [comment]
Fixed and I have added PWM outputs.
Thanks for report.
