### ISSUE TITLE
Pin header spacing

### ISSUE THREAD

**Issue by kacernator** [bigclownlabs/bc-website#39]
Please add spacing of the pin header to the website.
Thanks.

**Comment by hubmartin** [comment]
Hi,
for which spacing are you looking for? The dimensions between two pin headers is 10 "pins" which is 25.4 mm. The dimensions should be in drawings here.
https://www.bigclown.com/doc/hardware/header-pinout/
Have you found the information there?

**Comment by kacernator** [comment]
I mean between individual pins, e.g.  between P0 and P1.
I have one module in my hand and I measure 2.54mm.
It would be nice to have this information on your website "Header pinout".

**Comment by hubmartin** [comment]
Yes, we use standard 2.54 pin header. I've added this missing information to the first paragraph.
https://www.bigclown.com/doc/hardware/header-pinout/
