### ISSUE TITLE
How to testing MySigfox.com

### ISSUE THREAD

**Issue by HombreBigClown** [bigclownlabs/bc-website#48]
On https://www.bigclown.com/doc/tutorials/mysigfox-com-service/ 
The  https://requestb.in does not respond.
How can I test MySigfox?
Is it possible by https://ifttt.com?
Thx

**Comment by hubmartin** [comment]
Hello, those test services are constantly shutting down, but creating also others.

You can use https://requestbin.co/ 
Also you can try IFTTT HTTP WebHook, but it only triggers, you cannot inpect the parameters.
