### ISSUE TITLE
About Sensor Module - add connection details

### ISSUE THREAD

**Issue by kapitan-iglu** [bigclownlabs/bc-website#49]
Please add the following info to the [About Sensor Module](https://www.bigclown.com/doc/hardware/about-sensor-module/) docu page:
1. add image of rev 1.1 board
2. add connection examples
   - at least [photo](https://cdn.myshoptet.com/usr/shop.bigclown.com/user/shop/big/138-1_image--6.png?5bf40e4c) with 1-wire from e-shop page
   - optional typical connection of:
     - button (digital input)
     - LED (digital output)
     - pot (analog input)
     - 1-wire (external power and parasite power)

**Comment by hubmartin** [comment]
Hi, thanks for tips. I'll create these examples soon. I also plan to create some 1-wire code examples so I'll also add other usage scenarios.

**Comment by hubmartin** [comment]
Hi, I've added connection examples
http://localhost:1313/doc/hardware/about-sensor-module/

I've also updated Radio Pool Sensor project so now it supports also Sensor Module R1.1 and is using VDD pin for sensor powering. https://github.com/hubmartin/bcf-kit-wireless-pool-sensor
I also switched VCC and DATA signals so the connection it is now the same with Soil Moisture Sensor.

**Comment by kapitan-iglu** [comment]
Nice, that exactly what I've meant. Thanx.
